In [1]:
import numpy as np
import pandas as pd
data=pd.read_csv("data/datasets-165618-377201-metacritic_games.csv", index_col=1)
df=pd.DataFrame(data)
df.head()

,game,developer,genre,number_players,rating,release_date,positive_critics,neutral_critics,negative_critics,positive_users,neutral_users,negative_users,metascore,user_score
platform,,,,,,,,,,,,,,
PC,Portal 2,Valve Software,Action,NaN,E10+,"Apr 18, 2011",51,1,0,1700,107,19,95,90
PC,The Elder Scrolls V: Skyrim,Bethesda Game Studios,Role-Playing,No Online Multiplayer,M,"Nov 10, 2011",32,0,0,1616,322,451,94,82
3DS,The Legend of Zelda: Ocarina of Time 3D,GREZZO,Miscellaneous,No Online Multiplayer,E10+,"Jun 19, 2011",84,1,0,283,20,5,94,90
PC,Batman: Arkham City,Rocksteady Studios,Action Adventure,NaN,T,"Nov 21, 2011",27,0,0,240,34,27,91,87
3DS,Super Mario 3D Land,Nintendo,Action,No Online Multiplayer,E,"Nov 13, 2011",81,1,0,251,39,11,90,84

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5699 entries, PC to PS4
Data columns (total 14 columns):
game                5699 non-null object
developer           5685 non-null object
genre               5694 non-null object
number_players      3059 non-null object
rating              4433 non-null object
release_date        5699 non-null object
positive_critics    5699 non-null int64
neutral_critics     5699 non-null int64
negative_critics    5699 non-null int64
positive_users      5699 non-null int64
neutral_users       5699 non-null int64
negative_users      5699 non-null int64
metascore           5699 non-null int64
user_score          5699 non-null int64
dtypes: int64(8), object(6)
memory usage: 667.9+ KB

In [3]:
df.shape

(5699, 14)

In [4]:
df.columns=[col.lower() for col in df]
df.columns

Index(['game', 'developer', 'genre', 'number_players', 'rating',
       'release_date', 'positive_critics', 'neutral_critics',
       'negative_critics', 'positive_users', 'neutral_users', 'negative_users',
       'metascore', 'user_score'],
      dtype='object')

In [5]:
df.drop(["number_players", "rating"], axis=1, inplace=True)
df.columns

Index(['game', 'developer', 'genre', 'release_date', 'positive_critics',
       'neutral_critics', 'negative_critics', 'positive_users',
       'neutral_users', 'negative_users', 'metascore', 'user_score'],
      dtype='object')

In [6]:
df.isnull().sum()

game                 0
developer           14
genre                5
release_date         0
positive_critics     0
neutral_critics      0
negative_critics     0
positive_users       0
neutral_users        0
negative_users       0
metascore            0
user_score           0
dtype: int64

In [7]:
null_data = df[df.isnull().any(axis=1)]
null_data.shape

(14, 12)

In [9]:
df.dropna(inplace=True)
df.shape

(5685, 12)

In [10]:
df.head()

,game,developer,genre,release_date,positive_critics,neutral_critics,negative_critics,positive_users,neutral_users,negative_users,metascore,user_score
platform,,,,,,,,,,,,
PC,Portal 2,Valve Software,Action,"Apr 18, 2011",51,1,0,1700,107,19,95,90
PC,The Elder Scrolls V: Skyrim,Bethesda Game Studios,Role-Playing,"Nov 10, 2011",32,0,0,1616,322,451,94,82
3DS,The Legend of Zelda: Ocarina of Time 3D,GREZZO,Miscellaneous,"Jun 19, 2011",84,1,0,283,20,5,94,90
PC,Batman: Arkham City,Rocksteady Studios,Action Adventure,"Nov 21, 2011",27,0,0,240,34,27,91,87
3DS,Super Mario 3D Land,Nintendo,Action,"Nov 13, 2011",81,1,0,251,39,11,90,84

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5685 entries, PC to PS4
Data columns (total 12 columns):
game                5685 non-null object
developer           5685 non-null object
genre               5685 non-null object
release_date        5685 non-null object
positive_critics    5685 non-null int64
neutral_critics     5685 non-null int64
negative_critics    5685 non-null int64
positive_users      5685 non-null int64
neutral_users       5685 non-null int64
negative_users      5685 non-null int64
metascore           5685 non-null int64
user_score          5685 non-null int64
dtypes: int64(8), object(4)
memory usage: 577.4+ KB

In [12]:
df.describe()

,positive_critics,neutral_critics,negative_critics,positive_users,neutral_users,negative_users,metascore,user_score
count,5685.000000,5685.000000,5685.000000,5685.000000,5685.000000,5685.000000,5685.000000,5685.000000
mean,13.379595,7.971504,1.143712,28.813896,8.655761,14.404046,71.882850,67.168514
std,16.211865,7.702913,2.924501,103.807966,24.734058,85.040671,11.182417,13.543389
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,11.000000,4.000000
25%,3.000000,3.000000,0.000000,2.000000,1.000000,0.000000,66.000000,61.000000
50%,8.000000,6.000000,0.000000,5.000000,2.000000,1.000000,73.000000,70.000000
75%,17.000000,10.000000,1.000000,17.000000,6.000000,5.000000,80.000000,76.000000
max,118.000000,65.000000,51.000000,2762.000000,506.000000,2998.000000,97.000000,94.000000

In [13]:
df.corr()

,positive_critics,neutral_critics,negative_critics,positive_users,neutral_users,negative_users,metascore,user_score
positive_critics,1.000000,0.024712,-0.208504,0.498046,0.408567,0.172334,0.551287,0.334718
neutral_critics,0.024712,1.000000,0.255913,0.012166,0.148215,0.102000,-0.322350,-0.155497
negative_critics,-0.208504,0.255913,1.000000,-0.029547,0.021127,0.074013,-0.660420,-0.395424
positive_users,0.498046,0.012166,-0.029547,1.000000,0.714740,0.424680,0.234433,0.131309
neutral_users,0.408567,0.148215,0.021127,0.714740,1.000000,0.649928,0.161285,-0.023991
negative_users,0.172334,0.102000,0.074013,0.424680,0.649928,1.000000,0.033861,-0.201168
metascore,0.551287,-0.322350,-0.660420,0.234433,0.161285,0.033861,1.000000,0.547949
user_score,0.334718,-0.155497,-0.395424,0.131309,-0.023991,-0.201168,0.547949,1.000000

In [ ]:
df.to_csv("data/cleaned_datasets-165618-377201-metacritic_games.csv")